version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_DATABASE_PASSWORD=${REDIS_DATABASE_PASSWORD}
  redis:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "7000:6379"
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
